python evaluate.py \
  --task_name "scibench" \
  --file "thermo_standardized" \
  --propose_method "llama" \
  --value_method "local" \
  --mode "mcts" \
  --evaluate "scibench" \
  --verify_method "llm" \
  --iteration_limit 50 \
  --use_reflection "simple" \
  --branch 3 | tee test_evaluate.log